# Generated by Django 5.0 on 2024-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_branches_jobapplication_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': ' Brand', 'verbose_name_plural': ' Brands'},
        ),
        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name': 'Collaboration', 'verbose_name_plural': 'Collaborations'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': ' Color', 'verbose_name_plural': ' Colors'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': ' Favorite', 'verbose_name_plural': ' Favorite'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': ' Investment', 'verbose_name_plural': ' Investments'},
        ),
        migrations.AlterModelOptions(
            name='orderinvestment',
            options={'verbose_name': ' OrderInvestment', 'verbose_name_plural': ' OrderInvestments'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': ' OrderProduct', 'verbose_name_plural': ' OrderProducts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subfield',
            options={'verbose_name': ' Subfield', 'verbose_name_plural': ' Subfields'},
        ),
        migrations.AlterModelOptions(
            name='subfield_item',
            options={'verbose_name': ' Subfield_Item', 'verbose_name_plural': ' Subfield_Items'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='origin',
            new_name='origin_de',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='product_name',
            new_name='product_name_de',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='quality',
            new_name='quality_de',
        ),
        migrations.RenameField(
            model_name='collaboration',
            old_name='quantity',
            new_name='quantity_de',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='code',
            new_name='code_de',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='amount_invested',
            new_name='amount_invested_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='duration_staying_money',
            new_name='duration_staying_money_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='end_date',
            new_name='end_date_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='origin',
            new_name='origin_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='profitability_percentage',
            new_name='profitability_percentage_de',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='start_date',
            new_name='start_date_de',
        ),
        migrations.RenameField(
            model_name='orderinvestment',
            old_name='address',
            new_name='address_de',
        ),
        migrations.RenameField(
            model_name='orderinvestment',
            old_name='email',
            new_name='email_de',
        ),
        migrations.RenameField(
            model_name='orderinvestment',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='orderinvestment',
            old_name='phone_number',
            new_name='phone_number_de',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='address',
            new_name='address_de',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='email',
            new_name='email_de',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='phone_number',
            new_name='phone_number_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='information',
            new_name='information_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='origin',
            new_name='origin_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quality_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_de',
        ),
        migrations.RenameField(
            model_name='subfield',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='subfield_item',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='product_images',
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='description_en',
            field=models.TextField(default=None, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='description_fa',
            field=models.TextField(default=None, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='description_ru',
            field=models.TextField(default=None, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='description_tr',
            field=models.TextField(default=None, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='origin_en',
            field=models.CharField(default=None, max_length=255, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='origin_fa',
            field=models.CharField(default=None, max_length=255, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='origin_ru',
            field=models.CharField(default=None, max_length=255, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='origin_tr',
            field=models.CharField(default=None, max_length=255, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_de',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_en',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_fa',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_ru',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_tr',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_name_en',
            field=models.CharField(default=None, max_length=255, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_name_fa',
            field=models.CharField(default=None, max_length=255, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_name_ru',
            field=models.CharField(default=None, max_length=255, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_name_tr',
            field=models.CharField(default=None, max_length=255, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quality_en',
            field=models.CharField(default=None, max_length=255, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quality_fa',
            field=models.CharField(default=None, max_length=255, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quality_ru',
            field=models.CharField(default=None, max_length=255, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quality_tr',
            field=models.CharField(default=None, max_length=255, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quantity_en',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quantity_fa',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quantity_ru',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quantity_tr',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested_en',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='amount invested'),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested_fa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='amount invested'),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested_ru',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='amount invested'),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested_tr',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='amount invested'),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_fa',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_ru',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_tr',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_staying_money_en',
            field=models.IntegerField(default=None, help_text='Duration in months', verbose_name='duration_staying_money'),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_staying_money_fa',
            field=models.IntegerField(default=None, help_text='Duration in months', verbose_name='duration_staying_money'),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_staying_money_ru',
            field=models.IntegerField(default=None, help_text='Duration in months', verbose_name='duration_staying_money'),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_staying_money_tr',
            field=models.IntegerField(default=None, help_text='Duration in months', verbose_name='duration_staying_money'),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date_en',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date_fa',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date_ru',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date_tr',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='name_en',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='name_fa',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='name_ru',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='name_tr',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='origin_en',
            field=models.CharField(default=None, max_length=50, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='origin_fa',
            field=models.CharField(default=None, max_length=50, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='origin_ru',
            field=models.CharField(default=None, max_length=50, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='origin_tr',
            field=models.CharField(default=None, max_length=50, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability_percentage_en',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='profitability_percentage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability_percentage_fa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='profitability_percentage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability_percentage_ru',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='profitability_percentage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability_percentage_tr',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='profitability_percentage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date_en',
            field=models.DateField(default=None, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date_fa',
            field=models.DateField(default=None, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date_ru',
            field=models.DateField(default=None, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date_tr',
            field=models.DateField(default=None, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='address_en',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='address_fa',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='address_ru',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='address_tr',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='email_en',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='email_fa',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='email_ru',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='email_tr',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='name_en',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='name_fa',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='name_ru',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='name_tr',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='phone_number_en',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='phone_number_fa',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='phone_number_ru',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='phone_number_tr',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='address_en',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='address_fa',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='address_ru',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='address_tr',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='email_en',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='email_fa',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='email_ru',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='email_tr',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name_en',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name_fa',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name_ru',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name_tr',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number_en',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number_fa',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number_ru',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number_tr',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_fa',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_ru',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_tr',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_ru',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_tr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_fa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tr',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_ru',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_tr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_en',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_fa',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ru',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_tr',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='subfield',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield',
            name='name_fa',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield',
            name='name_tr',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield_item',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield_item',
            name='name_fa',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield_item',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield_item',
            name='name_tr',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
