# Generated by Django 5.0 on 2024-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_brand_options_alter_collaboration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='description_ar',
            field=models.TextField(default=None, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='origin_ar',
            field=models.CharField(default=None, max_length=255, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_images_ar',
            field=models.ImageField(default='default_image.jpg', upload_to='collaboration_images/', verbose_name='product_images'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='product_name_ar',
            field=models.CharField(default=None, max_length=255, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quality_ar',
            field=models.CharField(default=None, max_length=255, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='quantity_ar',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='color',
            name='code_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested_ar',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='amount invested'),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_ar',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='investment',
            name='duration_staying_money_ar',
            field=models.IntegerField(default=None, help_text='Duration in months', verbose_name='duration_staying_money'),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date_ar',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='name_ar',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='investment',
            name='origin_ar',
            field=models.CharField(default=None, max_length=50, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='profitability_percentage_ar',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='profitability_percentage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date_ar',
            field=models.DateField(default=None, verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='address_ar',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='email_ar',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='name_ar',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderinvestment',
            name='phone_number_ar',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='address_ar',
            field=models.TextField(default=None, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='email_ar',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name_ar',
            field=models.CharField(default=None, max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number_ar',
            field=models.CharField(default=None, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_ar',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_ar',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_ar',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='quality'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ar',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='subfield',
            name='name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield_item',
            name='name_ar',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
