# Generated by Django 5.0 on 2024-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='googleplus_url',
            field=models.URLField(blank=True, null=True, verbose_name='googleplus url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instagram url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True, verbose_name='pinterest url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='telegram url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter url'),
        ),
        migrations.AlterField(
            model_name='team',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='youtube url'),
        ),
    ]
