# Generated by Django 5.0 on 2024-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_alter_team_googleplus_url_alter_team_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='job_title',
            new_name='job_title_ar',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='team',
            name='description_de',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description_fa',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description_ru',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description_tr',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_de',
            field=models.CharField(default='', max_length=255, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_en',
            field=models.CharField(default='', max_length=255, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_fa',
            field=models.CharField(default='', max_length=255, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_ru',
            field=models.CharField(default='', max_length=255, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_tr',
            field=models.CharField(default='', max_length=255, verbose_name='job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name_de',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name_fa',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name_tr',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
