# Generated by Django 5.0 on 2024-01-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_rename_description_team_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_ar',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_ar',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_de',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_tr',
        ),
    ]
